### PR TITLE
Add compiled files for bower

### PR DESCRIPTION
**Pull request by grahamgilchrist**
#2 doesn't work, because of a third party module dependency on the main `bootstrap.tpls` module. Thsi provides a fully compiled version of the customised bootstrap to use via bower.

### CODE REVIEW

**Comment by grahamgilchrist** [comment]
@incuna/js Please review/merge. Undoes changes form #2 and replaces them with a distributed version of the full package

**Comment by henrahmagix** [comment]
Our seed project uses `0.11.0`, how come this outputs `0.10.0`?

**Comment by grahamgilchrist** [comment]
`package.json` says `0.10.0` ? Which seed project do you mean?

**Comment by grahamgilchrist** [comment]
These are basically the same files that are currently being generated in epatient projects, but just contain the entire bootstrap lib, rather than specific components. 

This makes using via bower a lot easier. Instead of our existing `grunt:shell` task, we can just include the javascript modules and compiled template files we want for the project.

**Comment by grahamgilchrist** [comment]
Also this is just a temporary fix for the existing project. Next time we need to use this significantly on a new project we should update from the upstream source repo properly.

**Comment by henrahmagix** [comment]
In that case, good to merge

On 12 March 2015 at 12:37, Graham Gilchrist notifications@github.com
wrote:

> Also this is just a temporary fix for the existing project. Next time we
> need to use this significantly on a new project we should update from the
> upstream source repo properly.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/incuna/bootstrap/pull/3#issuecomment-78471707.

## 

Henry Blyth - Developer
henry@incuna.com
01865 791 494
Incuna Ltd, 16 Middle Way, Oxford, OX2 7LH

**Pull request merged**
